<%@ Page Language="C#" Title="Delivery Address" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="DeliveryAddressForm.aspx.cs" Inherits="GoodFood.DeliveryAddressForm" %>

<asp:Content ID="DishForm" ContentPlaceHolderID="MainContent" runat="server">
    <div class="jumbotron">
        <div>
            <asp:Label ID="Label1" runat="server" Text="Delivery Address Form" CssClass="h3"></asp:Label>
        </div>
        <br />
        <div class="form-group">
            <asp:Label ID="Label3" runat="server" Text="Delivery Point"></asp:Label>
            <asp:TextBox ID="txtDeliveryPoint" runat="server" CssClass="form-control"></asp:TextBox>
            <asp:RequiredFieldValidator ID="rfvDP" runat="server" ErrorMessage="Delivery point required!" ControlToValidate="txtDeliveryPoint" ValidationGroup="DeliveryGroup" ForeColor="#FF5050"></asp:RequiredFieldValidator>
        </div>
        <div class="form-group">
            <asp:Label ID="Label4" runat="server" Text="Longitude"></asp:Label>
            <asp:TextBox ID="txtLongitude" runat="server" CssClass="form-control"></asp:TextBox>
            <asp:RequiredFieldValidator ID="rfvLong" runat="server" ErrorMessage="Longitude required!" ValidationGroup="DeliveryGroup" ControlToValidate="txtLongitude" ForeColor="#FF5050"></asp:RequiredFieldValidator>
        </div>
        <div class="form-group">
            <asp:Label ID="Label5" runat="server" Text="Latitude"></asp:Label>
            <asp:TextBox ID="txtLatitude" runat="server" CssClass="form-control"></asp:TextBox>
            <asp:RequiredFieldValidator ID="rfvLat" runat="server" ErrorMessage="Latitude required!" ValidationGroup="DeliveryGroup" ControlToValidate="txtLatitude" ForeColor="#FF5050"></asp:RequiredFieldValidator>
        </div>
        <div class="form-group">
            <asp:Button ID="btnInsert" runat="server" Text="Insert" OnClick="btnInsert_Click" CssClass="btn btn-primary" ValidationGroup="DeliveryGroup" />
        </div>
    </div>
    <br />
    <div class="form-group">
        <asp:label ID="Label2" runat="server" Text="Delivery Address Table" CssClass="h4"></asp:label>
    </div>
    <div class="form-group">
        <asp:GridView ID="GridView1" runat="server" CssClass="table table-hover" DataKeyNames="ADDRESS_ID" OnRowDataBound="OnRowDataBound" OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowUpdating="OnRowUpdating" OnRowDeleting="OnRowDeleting" EmptyDataText="No records has been added." AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"></asp:GridView>
    </div>
</asp:Content>
