<%@ Page Language="C#" Title="Dish" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="DishForm.aspx.cs" Inherits="GoodFood.DishForm" %>

<asp:Content ID="DishForm" ContentPlaceHolderID="MainContent" runat="server">
    <div class="jumbotron">
        <div>
            <asp:Label ID="Label1" runat="server" Text="Dish Form" CssClass="h3"></asp:Label>
        </div>
        <br />
        <div class="form-group">
            <asp:Label ID="Label2" runat="server" Text="Dish Code"></asp:Label>
            <asp:TextBox ID="txtCode" runat="server" CssClass="form-control"></asp:TextBox>
            <asp:RequiredFieldValidator ControlToValidate="txtCode" ID="rfvCode" runat="server" ErrorMessage="Code can not be empty." ForeColor="#FF5050" ValidationGroup="DishGroup"></asp:RequiredFieldValidator>
        </div>
        <div class="form-group">
            <asp:Label ID="Label3" runat="server" Text="Dish Name"></asp:Label>
            <asp:TextBox ID="txtName" runat="server" CssClass="form-control"></asp:TextBox>
            <asp:RequiredFieldValidator ControlToValidate="txtName" ID="rfvName" runat="server" ErrorMessage="Name can not be empty." ForeColor="#FF5050" ValidationGroup="DishGroup"></asp:RequiredFieldValidator>
        </div>
        <div class="form-group">
            <asp:Label ID="Label4" runat="server" Text="Another Name"></asp:Label>
            <asp:TextBox ID="txtAnotherName" runat="server" CssClass="form-control"></asp:TextBox>
        </div>
        <div class="form-group">
            <asp:Button ID="btnInsert" runat="server" Text="Insert" OnClick="btnInsert_Click" ValidationGroup="DishGroup" CssClass="btn btn-primary" />
        </div>
    </div>
    <br />
    <div class="form-group">
        <asp:Label ID="Label6" runat="server" Text="Dish Table" CssClass="h4"></asp:Label>
    </div>    
    <div>
        <asp:GridView ID="GridView1" runat="server" CssClass="table table-hover" DataKeyNames="DISH_ID" OnRowDataBound="OnRowDataBound" OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowUpdating="OnRowUpdating" OnRowDeleting="OnRowDeleting" EmptyDataText="No records has been added." AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"></asp:GridView>
    </div>
</asp:Content>
