<%@ Page Language="C#" Title="Loyalty Point" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="LoyaltyPointsForm.aspx.cs" Inherits="GoodFood.LoyaltyPointsForm" %>

<asp:Content ID="DishForm" ContentPlaceHolderID="MainContent" runat="server">
    <div class="jumbotron">
        <div>
            <asp:Label ID="Label1" runat="server" Text="Loyalty Point Form" CssClass="h3"></asp:Label>
        </div>
        <br />
        <div class="form-group">
            <asp:Label ID="Label2" runat="server" Text="Loyalty Point"></asp:Label>
            <asp:TextBox ID="txtLoyaltyPoint" runat="server" CssClass="form-control"></asp:TextBox>
            <asp:RequiredFieldValidator ID="rfvLoyal" runat="server" ErrorMessage="Loyalty points required!" ControlToValidate="txtLoyaltyPoint" ForeColor="#FF5050" ValidationGroup="LoyalGroup"></asp:RequiredFieldValidator>
        </div>
        <div class="form-group">
            <asp:Label ID="Label3" runat="server" Text="Start Date (MM/DD/YYYY)"></asp:Label>
            <asp:TextBox ID="txtStartDate" runat="server" CssClass="form-control"></asp:TextBox>
            <asp:RequiredFieldValidator ID="rfvStart" runat="server" ErrorMessage="Start date required!" ControlToValidate="txtStartDate" ForeColor="#FF5050" ValidationGroup="LoyalGroup"></asp:RequiredFieldValidator>
        </div>
        <div class="form-group">
            <asp:Label ID="Label4" runat="server" Text="End Date (MM/DD/YYYY)"></asp:Label>
            <asp:TextBox ID="txtEndDate" runat="server" CssClass="form-control"></asp:TextBox>
            <asp:RequiredFieldValidator ID="rfvEnd" runat="server" ErrorMessage="End date required!" ForeColor="#FF5050" ValidationGroup="LoyalGroup" ControlToValidate="txtEndDate"></asp:RequiredFieldValidator>
        </div>
        <div class="form-group">
            <asp:Button ID="btnInsert" runat="server" Text="Insert" OnClick="btnInsert_Click" CssClass="btn btn-primary" ValidationGroup="LoyalGroup" />
        </div>
    </div>
    <br />
    <div class="form-group">
        <asp:Label ID="Label5" runat="server" Text="Loyalty Points Table" CssClass="h4"></asp:Label>
    </div>
    <div>
        <asp:GridView ID="GridView1" runat="server" CssClass="table table-hover" DataKeyNames="LOYALTY_ID" OnRowDataBound="OnRowDataBound" OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowUpdating="OnRowUpdating" OnRowDeleting="OnRowDeleting" EmptyDataText="No records has been added." AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"></asp:GridView>
    </div>
</asp:Content>
