<%@ Page Language="C#" Title="Restaurant" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="RestaurantForm.aspx.cs" Inherits="GoodFood.RestaurantForm" %>

<asp:Content ID="DishForm" ContentPlaceHolderID="MainContent" runat="server">
    <div class="jumbotron">
        <div>
            <asp:Label ID="Label2" runat="server" Text="Restaurant Form" CssClass="h3"></asp:Label>
        </div>
        <br />
        <div class="form-group">
            <asp:Label ID="Label3" runat="server" Text="Restaurant Name"></asp:Label>
            <asp:TextBox ID="txtResName" runat="server" CssClass="form-control"></asp:TextBox>
            <asp:RequiredFieldValidator ID="rfvName" runat="server" ErrorMessage="Name required!" ForeColor="#FF5050" ControlToValidate="txtResName" ValidationGroup="ResGroup"></asp:RequiredFieldValidator>
        </div>
        <div class="form-group">
            <asp:Label ID="Label4" runat="server" Text="Restaurant Address"></asp:Label>
            <asp:TextBox ID="txtResAddress" runat="server" CssClass="form-control"></asp:TextBox>
            <asp:RequiredFieldValidator ID="rfvAddress" runat="server" ErrorMessage="Address required!" ControlToValidate="txtResAddress" ForeColor="#FF5050" ValidationGroup="ResGroup"></asp:RequiredFieldValidator>
        </div>
        <div class="form-group">
            <asp:Button ID="btnInsert" runat="server" Text="Insert" OnClick="btnInsert_Click" CssClass="btn btn-primary" ValidationGroup="ResGroup" />
        </div>
    </div>
    <br />
    <div class="form-group">
        <asp:Label ID="Label1" runat="server" Text="Restaurant table" CssClass="h4"></asp:Label>
    </div>
    <div class="form-group">
        <asp:GridView ID="GridView1" runat="server" CssClass="table table-hover" DataKeyNames="RESTAURANT_ID" OnRowDataBound="OnRowDataBound" OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowUpdating="OnRowUpdating" OnRowDeleting="OnRowDeleting" EmptyDataText="No records has been added." AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"></asp:GridView>
    </div>
</asp:Content>
